name: twobody

channels:
  - astropy

dependencies:
  - python=3.6
  - pyqt=5.6.0
  - astropy
  - numpy
  - scipy
  - matplotlib=2.1.2
  - jupyter
  - pandas
  - pytables
  - cython
  - pip=9.0.1
  - pip:
     - git+https://github.com/adrn/twobody
